site_name: 山高水长，路遥马急
site_url: https://Goray_GuoLei.github.io/mymkdocs/
site_author: 郭磊（Goray_GuoLei）
# theme:
  
#   palette:
#     primary: indigo #顶部颜色
theme:
  name: material
  language: zh # 一些提示性的文字会变成中文
  # 明亮模式
  palette: 
    # - primary: indigo #顶部颜色
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
  - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant
    #- header.autohide  #自动隐藏
  - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
  - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
  - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
  - navigation.top # 返回顶部的按钮 在上滑时出现
  - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
  - search.suggest # 搜索输入一些字母时推荐补全整个单词
  - search.highlight # 搜索出的文章关键词加入高亮
  - search.share #搜索分享按钮
  - navigation.expand # 打开Tab时左侧目录全部展开
  - navigation.indexes #启用节索引页后，可以将文档直接附加到节
  - content.tabs.link
  - content.tooltips
  - content.code.copy #代码复制
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - navigation.top  # 确保启用返回顶部按钮（可选）




nav: 
  # - MkDocs : index.md

  - 算法与数据结构 :
    - 算法模版 : code/demo.md
    - 每日一题 : code/daily-question.md

  - 专业课程:
    - C: Tutorial/C.md
    - Java: Tutorial/Java.md
    - Python: Tutorial/Python.md
  
  - 博客:
    - blog/index.md
  
  - 留言板: discussion.md

  - 随笔便签: mood/some-tips.md
    
  
  - 关于我 : aboutme.md



extra:
  #这段语言转换暂时不做，有需要的话再看
  # alternate:
  #   - name: 简体中文
  #     link: 
  #     #https://wcowin-work.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp
  #     lang: zh   
  #   - name: English
  #     link: https://wcowin-work.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp 
  #     lang: en
  #   - name: 中国(台湾)
  #     link: https://wcowin-work.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=zh-TW&_x_tr_hl=zh-CN&_x_tr_pto=wapp
  #     lang: zh-TW
  generator: true #是否删除页脚显示“使用 MkDocs 材料制造”
  #联系方式
  social:
    #微信联系方式
    - icon: fontawesome/brands/weixin
      link: https://s1.imagehub.cc/images/2025/04/17/8e29442feac3ebaf95881587c72e7cdb.jpg
      name: wechat
    #TG联系方式
    - icon: fontawesome/brands/telegram
      link: https://t.me/sgsclymj
      name: telegram
    # - icon: fontawesome/brands/x-twitter #联系方式图标 : https://fontawesome.com/ 去这里找图标
    #   link: https://twitter.com/wcowin_
    #github联系方式
    - icon: fontawesome/brands/github
      link: https://github.com/Goray_GuoLei
    #邮箱联系方式
    - icon: fontawesome/regular/envelope #联系方式图标
      link: mailto:<lei774793@gmail.com> #邮件联系方式
    #b站主页
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/387019777

  analytics:
    provider: google #谷歌分析
    property:  ##如果你 clone 了my模板，请将这个修改为你的

    # 网页底部反馈
    feedback:
      title: 此页面有帮助吗？
      ratings:
        - icon: material/thumb-up-outline #图标可自定义
          name: This page was helpful
          data: 1
          note: >-
            谢谢你的反馈！
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  # cookies设置（可选）
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
  #     如果你同意,你可以帮助我们让我们的网站更好
plugins:
  - search #搜索配置
  - git-committers:
      enabled: !ENV [git-committers, false]
      repository: Wcowin/Mkdocs-Wcowin
      branch: main
      exclude:
        - index.md
        - tag.md
        - liuyanban.md
        - blog/posts/update.md
        - blog/posts/wkw.md
        - about/link.md
  - git-revision-date-localized:
      enabled: !ENV [git-revision-date-localized, false]
      type: iso_date
      enable_creation_date: false
      exclude:
        - index.md
        - tag.md
        - liuyanban.md
        - blog/posts/update.md
        - blog/posts/wkw.md
        - about/link.md
        - websitebeauty/linktech.md
  - blog: #博客配置
      post_date_format: full #时间
      draft: true
      draft_if_future_date: true #自动将具有未来日期的帖子标记为草稿
      post_readtime: true
      post_readtime_words_per_minute: 265 #计算帖子的阅读时间时读者每分钟预计阅读的字数
      post_url_format: "{date}/{slug}"
      # categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml" #作者信息
  - tags

# extra_css:
#   - css/custom.css